name: ms-carrinho

services:
  web-carrinho:
    image: node
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    working_dir: /app

    # Pode ser usado para rodar um shell, por exemplo `sh ./entrypoint.sh`.
    command: >
      sh -c "npm install &&
             npm run dev" 
    env_file: ".env"
    ports:
      - 3000:3000
    depends_on:
      - mongo-carrinho
      # - rabbitmq

  mongo-carrinho:
    image: mongo
    env_file: "mongo-container.env"

  # rabbitmq:
  #   image: rabbitmq
  #   env_file: "rabbitmq-container.env"
  #   ports:
  #     - 5672:5672
