name: ms-carrinho

services:
  web-carrinho:
    image: node
    volumes:
      - ./:/app
    working_dir: /app
    command: npm start # Pode ser usado para rodar um shell, por exemplo `sh ./entrypoint.sh`.
    env_file: ".env"
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
      - mongo-carrinho

  mongo-carrinho:
    image: mongo
    env_file: "mongo-container.env"

  rabbitmq:
    image: rabbitmq
    env_file: "rabbitmq-container.env"
    ports:
      - 5672:5672
