name: ms-carrinho

services:
  web-carrinho:
    image: node:20
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    working_dir: /app

    # Pode ser usado para rodar um shell, por exemplo `sh ./entrypoint.sh`.
    command: >
      "npm install &&
      npm run dev" 
    env_file: ".env.local"
    ports:
      - 3000:3000
    depends_on:
      - mongo-carrinho
      - rabbitmq

  mongo-carrinho:
    image: mongo
    env_file: "mongo-container.env"

  rabbitmq:
    image: rabbitmq:3.13-management
    env_file: "rabbitmq-container.env"
    # volumes:
    #   - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

# volumes:
#   rabbitmq-data:
#     # external: true
#     name: rabbitmq-data